### ISSUE TITLE
Reason to use numeric keys and nesting?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/data-quality-spec#3]
@pwalsh 
I'm starting to work on goodtables.next more closely and this spec is a great source for me. But I have a few questions.

First is why to use this numbered keys instead of unique identifier of error. I don't fully understand where this numbers could be used because showing to user things like `error: structure-3` in my opinion less usable then something like `error: structure-duplicate-row`. We have an experience working with linters and I suppose all don't like when they starting to answer to us with some strange numeric codes (ok if you have 200 different error it could be explained). 

Second is `format/structure/schema` nesting. I see here also room for simplification. We have like around 30 errors I suppose we could to write it just is simplest dict form like:

```
unknown-format:
    type: format
    ...
unknown-encoding:
    type: format
    ...
blank-header:
    type: structure
    ...
missing-headers:
    type: schema
    ...
pattern-constraint:
   type: schema
```

It also allow to introduce some **unified language** between users and implementations e.g. there will be `check_missing_headers` or `checkPatternConstraint` (in js). Or in some validator - `validate(checks={'missing-headers': True})`.

Also do you plan tools could use this spec programaticaly? If yes then my comments are even more actual I suppose.
